### ISSUE TITLE
Data sent over HTTP: deal with both string and object

### ISSUE THREAD

**Issue by sylouuu** [PabloVallejo/gillie#11]
Hi @PabloVallejo,

Sometimes you want to send all your form by HTTP, so this is correct:

```js
submit: function () {
    this.Post('/something', 'form.sent', { data: $('form').serialize() });
}
```

Sometimes you want to send specific values:

```js
submit: function () {
    // Option 1
    // ------------------------------
    
    var data = {
        a: 'b',
        c: 'd'
    };
    
    // The idea is to skip this:
    data = decodeURIComponent($.param(data));
    
    // Option 2
    // ------------------------------
    
    var data = 'a=b&c=d',
        
    this.Post('/something', 'form.sent', { data: data });
}
```

The `Option 1` is more clear especially if your values are not statics. This could be achieved by checking the variable type. 

What do you think?

Bests

**Comment by PabloVallejo** [comment]
@sylouuu I think this is a good idea, I will take a look at it and ask you for 
feedback once I get home. Thanks :+1:

**Comment by PabloVallejo** [comment]
Hi @sylouuu thanks for creating the issue, I'm sorry for taking a look at it that late.

There are two things:

First: Once you have the model data set like this, there's no need to specify it in the request method.

```js
var Person = Gillie.Model.extend({
 
   default: {
      name: 'Not specified'
   }

    // Create person
    create: function() {
        
        // Post/Get/Put/Delete methods will sent current model attributes as request sent `data`.
        this.Post( 'person/', 'model.create' );
    }

});
```

Second: As you said, there might be useful to allow only specific attributes to be sent. In that case, I think we can add an option `allow` to the `options` object in order to specify which attributes get sent in the request.


```js
submit: function () {

    // Send the request with only `one` and `two` attributes as data.
    this.Post( '/url', 'event', { 'allow': [ 'one', 'two' ], data: $('form').serialize() });
}
```

Which is equivalent to:

```js
submit: function () {

    // Get form data as a hash.
    var data = $('form').serializeHash();

    // Set form data to model.
    this.set(data);
   
    // Send the request with only `one` and `two` attributes as data.
    this.Post( '/url', 'event', { 'allow': [ 'one', 'two' ] });
}

```

Do you thing this might be a fit for your case?

Best wishes.

**Comment by sylouuu** [comment]
Hello,

I don't use the first option.

For some cases, you don't have a form to sent, but mixed data (dynamic and static).

In your last example, why `allow` is an array and not an object? You could pass some key/value pairs.

Bests

**Comment by PabloVallejo** [comment]
Hi @sylouuu, perfect, I get it now.

What happens is that when you have data in the model attributes and send a request, that data is converted to a JSON string using `JSON.stringify`, however, when you pass the data in options as `{ data: {} }` it is not converted to JSON.

One thing you can do is to send data using `attrs` attribute in the `options` object like this.

```javascript
submit: function () {

    var data = {
        a: 'b',
        c: 'd'
    };

    this.Post( '/something', 'form.sent', { attrs: data } );
}
```

In this way, data will be parsed using `JSON.stringify` and there will be no need to use `$.param()`.
https://github.com/PabloVallejo/gillie/blob/master/gillie.js#L401

Let me know if this helps you.

Best wishes.

**Comment by sylouuu** [comment]
Hi @PabloVallejo,

I don't remember where I had this "problem". I think that I can close this issue without testing your solution. I'll go back here if needed.

Thank you!

**Comment by PabloVallejo** [comment]
You're welcome :+1
